id: productCategory
name: Product Category
created: '2024-08-06T06:56:44.515771+00:00'
updated: '2024-08-30T06:12:13.429129+00:00'
slugSettings:
  required: 'no'
useTeamPermissions: true
fields:
  - id: title
    name: Title
    type: text
    helpText: ''
    typeConfig: null
    localizable: true
  - id: description
    name: Description
    type: text
    helpText: ''
    typeConfig: null
    localizable: true
  - id: logo
    name: Logo
    type: asset
    helpText: ''
    typeConfig:
      max: 1
    localizable: true
  - id: displayPriority
    name: Display Priority
    type: checkbox
    helpText: >-
      Check to mark this filter as a high-priority. Filters with the
      high-priority will appear at the top of the list in filter box
    typeConfig: null
entryName: title
thumbnailField: logo
description: ''
icon: edit-fade
type: contentType
permissions: []
