id: productReview
displayName: Product Review
ttl: 30
path: /single
custom:
  proposedName: Testimonial
  allowedContentTypes:
    - testimonial
method: GET
purgeKey: a0b281db-caed-4632-b2c6-006bd39dbdff
archetype: singleEntry
variables:
  entryId:
    type: text
    default: ''
dataSourceId: uniformContent
allowedOnComponents: []
