id: productCatalogItem
displayName: Product Catalog Item
ttl: 30
path: /api/products/get-by-ids
custom:
  proposedName: Product
  selectedCategoryIds:
    - '23'
    - '27'
  selectedDisplayField: name
method: GET
purgeKey: ee6e7418-ac5e-4a15-abdf-2827fc94fd85
archetype: singleProduct
variables:
  page:
    type: text
    default: '1'
    displayName: Page
  limit:
    type: text
    default: ''
    displayName: Limit
  keyword:
    type: text
    default: ''
    displayName: Keyword
  sortField:
    type: text
    default: ''
    displayName: Sort Field
  categoryId:
    type: text
    default: ''
    displayName: Category Id
  productIds:
    type: text
    default: ''
    helpText: Array of product ids
    displayName: Product Ids
  sortDirection:
    type: text
    default: ''
    displayName: Sort Direction
parameters:
  - key: id
    value: ${productIds}
  - key: categoryId
    value: ${categoryId}
  - key: keyword
    value: ${keyword}
  - key: sortField
    value: ${sortField}
  - key: sortDirection
    value: ${sortDirection}
  - key: limit
    value: ${limit}
  - key: page
    value: ${page}
dataSourceId: pim
allowedOnComponents: []
