id: productCategoryList
displayName: Product Category List
path: /query
custom:
  allowedContentTypes:
    - productCategory
method: GET
purgeKey: 86b84a0c-02b9-4217-b3d4-ce9a858ffad5
archetype: queryEntries
variables:
  limit:
    type: text
    default: '20'
  offset:
    type: text
    default: '0'
  filters:
    type: text
    default: '{}'
  orderBy:
    type: text
    default: ''
  contentTypes:
    type: text
    default: ''
dataSourceId: uniformContent
allowedOnComponents: []
